language: node_js
node_js: 
  - "10"
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: Run Lint and Tests
      script: 
        - npm run lint
        - npm run test
    - stage: Publish on NPM
      script: npm publish
      on:
        branch: master