language: node_js
node_js: 
  - "10"
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: Run Lint
      script: npm run lint
    - stage: Run Tests
      script: npm test
    - stage: Publish on NPM
      script: npm publish
      on:
        branch: master